### ISSUE TITLE
Serialization & Deserialization

### ISSUE THREAD

**Issue by kafechew** [erelsgl/limdu#25]
I'm having issues with the Serialisation and Deserialisation for combination of limdu + serialization npm packages.

Normally, we will serialise into a .json file. 
Using serialize.toString(), I don't where is the serialized .json file.

Q1. Maybe limdu/serialization will not generate the .json file?

Anyone can enlighten? 
Thanks.

**Comment by erelsgl** [comment]
Hi Kai,

The function serialize.toString does not automatically generate a json file. It only returns a string.

To save the string to a file, you can use the standard writeFile or writeFileSync function of the fs library, see here:
https://nodejs.org/api/all.html#all_fs_writefile_filename_data_options_callback

For example:
        var fs = require('fs');
        var classifierString = serialize.toString(intentClassifier, newClassifierFunction);
	fs.writeFileSync("myFileName.json", classifierString);

**Comment by kafechew** [comment]
You're so cool!

Let's say I had saved the string to "myFileName.json" as suggested... 
and send into remote server folder, "/myFolder".
How to initialize the deserialization?

My guess: 

> var intentClassifierCopy = serialize.fromString(intentClassifierString, myFolder/myFileName.json); 

Am I right?

Thanks again!

**Comment by erelsgl** [comment]
In order to deserialize, you first have to read the string from the file, like this:

    var intentClassifierString = fs.readFileSync("myFolder/myFileName.json");
    var intentClassifierCopy = serialize.fromString(intentClassifierString, __dirname);

**Comment by kafechew** [comment]
Working great! 
I had migrated from natural to limdu!
Thank you very much!

**Comment by kafechew** [comment]
@erelsgl 
The above, we will store the .json files as local files in the remote server.
What if the .json file is an external file, not a local file?
Instead of moving the files to remote server, can the remote server directly call the .json from the original server?

Can we deserialise the external .json (http://anotherweb/json/myFileName.json) ?

My guess:

var intentClassifierString = fs.readFileSync("http://anotherweb/json/myFileName.json");
var intentClassifierCopy = serialize.fromString(intentClassifierString);

Can you confirm that?
Thanks in advanced.

**Comment by erelsgl** [comment]
Hi Kai,

I think readFileSync works only with local files.

To download a remote file, try the suggestions here:
http://stackoverflow.com/questions/11944932/how-to-download-a-file-with-node-js

**Comment by kafechew** [comment]
@erelsgl 
You're right. Just solved through alike method as you suggested, i.e. xhr 
Things are interesting now!
Thanks again!! :-)
