### ISSUE TITLE
Languages supported?

### ISSUE THREAD

**Issue by kafechew** [erelsgl/limdu#27]
What are the languages supported for the limdu classifications?
I assume all the language using a-z alphabet.

How's about the Hebrew, Chinese, Hindi, Korea... those are not a-z alphabet?

Thanks :-)

**Comment by erelsgl** [comment]
Hi Kai,

limdu should work for any language. If you encounter any specific problem
in working with limdu in your language, please report it and we will check.

Erel

**Comment by kafechew** [comment]
Cool~ Noted with thanks~

**Comment by kafechew** [comment]
I'm trying to analyse the Chinese.
For english, in which 1-gram of word will be simple and straight forward... 
like "I am Max" will become "I", "am", "Max"

The problem with Chinese, different from english, it doesn't have "space".
我是马氏 (something like IamMax)
So, it will become "我是马氏" or ("IamMax"), instead of "我", "是", "马", "氏" ("I", "am", "Max")

Do you have any solution with Limdu for this kind of issue (Tokenisation)?
Thanks in advanced!

**Comment by erelsgl** [comment]
Hi Kai,

Currently limdu contains only a small number of feature extractors, which
are used mainly as examples. There is a feature extractor that extracts
words: "limdu.features.NGramsOfWords", and one that extracts letters: "
limdu.features.NGramsOfLetters".   You can try to use the second one and
see if it works.

**Comment by kafechew** [comment]
Hi erelsgl,

Yep. Referring to my previous comment, I'm using both at this moment.
Just looking for better recommendations :-)
Thanks~
