### ISSUE TITLE
Meaning of Retraining?

### ISSUE THREAD

**Issue by kafechew** [erelsgl/limdu#29]
// Initialize a classifier with a feature extractor:
    return new limdu.classifiers.EnhancedClassifier({
        classifierType: TextClassifier,
        featureExtractor: WordExtractor,
        pastTrainingSamples: [], // to enable retraining
    });

What's the meaning of the "retraining"?
What's the benefits of enabling "retraining"?

Thanks :-)

**Comment by erelsgl** [comment]
In online classifiers, if you train the classifier again on the same training samples, you often get slightly better results. To do this, you just call the ".retrain()" method of the classifier.
