### ISSUE TITLE
Continuous learning

### ISSUE THREAD

**Issue by thebergamo** [erelsgl/limdu#30]
Hi!

How I can improve my ML to continue learning? I cannot putting all inputs in the world. But how limdu can learn about new inputs? Like categories classification?

Or an example like this:

I have 3 documents and I need parse and categorizing. The first are talking about node, the seconds is about JS but the last are talking about Cook! But my train not have any examples about cook!

How I can add a new input for limdu understand how is Cook and Cook are the real good word for this categorie?

**Comment by erelsgl** [comment]
The documentation section "Online Learning" gives an example of what you want to do.
