### ISSUE TITLE
Example Result

### ISSUE THREAD

**Issue by PSeitz** [erelsgl/limdu#34]
The result from the example differs:
Feature extraction - converting an input sample into feature-value pairs

result:
[ expansioned: {},
  features: { I: 1, want: 1, an: 1, apple: 1, and: 1, a: 1, banana: 1 } ]
[ expansioned: {},
  features: { I: 1, WANT: 1, AN: 1, APPLE: 1, AND: 1, A: 1, BANANA: 1 } ]

**Comment by erelsgl** [comment]
This was a bug. I fixed it. Thanks for reporting.
