### ISSUE TITLE
Synaptic

### ISSUE THREAD

**Issue by SkY3r** [erelsgl/limdu#35]
Please use Synaptic in the next version Limdu :D

https://www.npmjs.com/package/synaptic

**Comment by erelsgl** [comment]
Looks like a useful addition. Would you like to add a plug-in?

**Comment by SkY3r** [comment]
We are happy to take care of this! : D It's your repository so the question of library and replace the old code is not updated repository "brain" to "synaptic" or perhaps add just add it as an add-on?

**Comment by erelsgl** [comment]
Can you add it as an add-on?

**Comment by SkY3r** [comment]
Yes :D Already started :P

**Comment by I-n-d-e-r** [comment]
Limdu and Synaptic: #41 

Enjoy ;)

**Comment by erelsgl** [comment]
Thank you very much for the contribution. We are working on it.

*--- Erel Segal-Halevi   (http://erelsgl.github.io
<http://erelsgl.github.io>) אראל סגל הלוי*

**Comment by erelsgl** [comment]
Dear Inder,
The new classifier looks fine!
Can you please add a test file in the test
<https://github.com/erelsgl/limdu/tree/master/test>/*classifiersTest*
folder?
Thanks!

*--- Erel Segal-Halevi   (http://erelsgl.github.io
<http://erelsgl.github.io>) אראל סגל הלוי*
