### ISSUE TITLE
SvmLinear not functioning in new update

### ISSUE THREAD

**Issue by cyrus000** [erelsgl/limdu#36]
undefined function https://github.com/erelsgl/limdu/blob/master/classifiers/svm/SvmLinear.js#L37

moving https://github.com/erelsgl/limdu/blob/master/classifiers/svm/SvmLinear.js#L46 up and renameing L36 function doesn't fix issues in this file as well. the command string isn't valid. 

https://github.com/erelsgl/limdu/blob/master/classifiers/svm/SvmLinear.js#L102

**Comment by erelsgl** [comment]
I will check this in a week. Thanks for notifying.

**Comment by vaskonov** [comment]
@cyrus000, fixed.

Please take a look. Let me know if it doesn't work.
