### ISSUE TITLE
CrossValidation example issue

### ISSUE THREAD

**Issue by silentrob** [erelsgl/limdu#37]
`limdu.utils.test(...)` does not seem to exist, is there a new API to test the cross validation.

**Comment by erelsgl** [comment]
I will check this in a week. Thanks for notifying.

**Comment by silentrob** [comment]
I see it is removed here: https://github.com/erelsgl/limdu/blob/master/utils/index.js#L8

**Comment by vaskonov** [comment]
@silentrob, trainAndTest were moved to nlu-server repository as more data-oriented routine. 
PrecisionRecall.js does have confusion matrix implementation. 
Please let me know if you have further questions.

**Comment by vaskonov** [comment]
@silentrob, Please take a look at classifiers/svm/SvmLinearDemo.js

Here you can find an example how to define SvmLinear classifier.
Let me know if it's not helpfull.

**Comment by silentrob** [comment]
Just to be clear, I was following the example on the main readme and ran into the problem. I was looking more specifically for an example that does folding and cross validation. The SVM demo looks great, but not want I needed (yet). The nlu-server wouldn't run last time I tried either.

**Comment by vaskonov** [comment]
I've added SvmLinear example that uses cross-validation.
Please take a look classifiers/svm/SvmLinearDemo.js

**Comment by silentrob** [comment]
Oh that looks great, thanks!
