### ISSUE TITLE
Explainations

### ISSUE THREAD

**Issue by ianfabs** [erelsgl/limdu#42]
Could you please provide a more detailed overview of how the explanations system works, and what the math behind it is? I am having a little difficulty understanding the maths of certain explainations.

**Comment by erelsgl** [comment]
The explanation system is not very structured. The explanations are just
plain text sentences and are created differently in each classifier type.
If you have a difficulty with a specific explanation, please show  the code
and the results and I will try to help.

*--- Erel Segal-Halevi   (http://erelsgl.github.io
<http://erelsgl.github.io>) אראל סגל הלוי*
