### ISSUE TITLE
Online Learning

### ISSUE THREAD

**Issue by oritwoen** [erelsgl/limdu#44]
Hi, although I owe you underpaid pull request (I can not find the time to finish it), but I want to ask you something.

How does "trainOnline" learning in real time? From what I noticed the whole network is stored in memory and updated at the same time after adding a new variable?

With each new word network learns more slowly and after some time, and after a certain amount of memory the words no longer stand and comes in console error associated with the lack of memory.

With your hand you have any comments you would like to solve? You can use streams?

**Comment by erelsgl** [comment]
​Dear Inder,
"trainOnline" works differently for different types of classifiers.
There are classifiers that do not support online training at all (e.g. SVM).
Can you give a specific code example that causes problems for you?

*--- Erel Segal-Halevi   (http://erelsgl.github.io
<http://erelsgl.github.io>) אראל סגל הלוי*

**Comment by I-n-d-e-r** [comment]
Last time I checked it was using NodeJS 6.9.

Using n-grams and winnow if it is a small data set it all works fine and accordingly terminates. However, if you use a very large data set, about a million words and meanings (own wordnet) at the beginning of works fine, but after coming to some 50,000 - 100,000 results terminal abruptly terminates the process and returns the response: "memory leak". Added to this is the issue that it really is impossible to save such a large network file node also has memory problems when you try to save something so big.

```js
var TextClassifier = limdu.classifiers.multilabel.BinaryRelevance.bind(0, {
    binaryClassifierType: limdu.classifiers.Winnow.bind(0, {retrain_count: 10})
});

// Initialize a classifier with a feature extractor:
return new limdu.classifiers.EnhancedClassifier({
    classifierType: TextClassifier,
    featureExtractor: limdu.features.NGramsOfWords(1),
    pastTrainingSamples: [], // to enable retraining
});
```js
