### ISSUE TITLE
Command failed

### ISSUE THREAD

**Issue by rn3w** [erelsgl/limdu#45]
Error: Command failed: liblinear_train -c 20 tempfiles/SvmLinearDemo_14799415844
74_7224.learn tempfiles/SvmLinearDemo_1479941584474_7224.model

**Comment by erelsgl** [comment]
What code did you run?

*--- Erel Segal-Halevi   (http://erelsgl.github.io
<http://erelsgl.github.io>) אראל סגל הלוי*

**Comment by erelsgl** [comment]
Closing this issue since there is no code example
