### ISSUE TITLE
SVM wrapper doesn't work

### ISSUE THREAD

**Issue by corradodebari** [erelsgl/limdu#48]
HI.
I'm trying to use external SVM wrappers, as suggested by you, like svm_perf_learn, but even if I put in PATH, I've got this issue:
**Cannot find the executable 'svm_perf_learn'. Please download it from the SvmPerf website, and put a link to it in your path.
C:\Users\a\node_modules\limdu\classifiers\svm\SvmPerf.js:29
                throw new Error(msg);**
It's quite weird because in SvmPerf.js the check it's always true. 
Thanks

**Comment by ozzie1998** [comment]
Sorry, who are you again? I've not heard from you and I don't remember recommending SVM wrappers to you.

**Comment by corradodebari** [comment]
Hi. Sure, we've never been in touch before. I'm referring to [documentation](https://github.com/erelsgl/limdu) that talks about SVM wrapper to avoid quadratic progression in learning time.

**Comment by erelsgl** [comment]
What operating system do you use?
What do you get if you go to the command line and write:
"*svm_perf_learn"*
*?*

*--- Erel Segal-Halevi   (http://erelsgl.github.io
<http://erelsgl.github.io>) אראל סגל הלוי*

**Comment by ozzie1998** [comment]
Ofc, god I really am loosing my mind...

**Comment by corradodebari** [comment]
I'm working on Windows 10 (x64). If I run svm_perf_learn I've got:
**Not enough input parameters!**
Anyway I've used native libraries for textract in the same path and this one works.
Looking in the source code on-line, the check:
 if (!SvmPerf.isInstalled()) {
	 	var msg = "Cannot find the executable 'svm_perf_learn'. Please download it from the SvmPerf website, and put a link to it in your path.";
	 	console.error(msg)
	 	throw new Error(msg); 
	}
it will never be false, because SvmPerf.isInstalled() always return true. 
It seems to me that what I get from npm is not aligned to source code.

**Comment by vaskonov** [comment]
@corradodebari, please, open the following folder` limdu/classifiers/svm`
and run `node SvmPerfDemo.js`
and print here the output.
Thank you.

**Comment by corradodebari** [comment]
This the output:

C:\Users\c\Desktop\package\classifiers\svm>svm_perf_learn

Not enough input parameters!


(more)

SVM-struct learning module: SVM-perf, V3.00, 15.07.2009
^C
C:\Users\c\Desktop\package\classifiers\svm>node SvmPerfDemo.js
a: No such file or directory
Cannot find the executable 'svm_perf_learn'. Please download it from the SvmPerf website, and put a link to it in your path.
C:\Users\c\Desktop\package\classifiers\svm\SvmPerf.js:29
                throw new Error(msg);
                ^

Error: Cannot find the executable 'svm_perf_learn'. Please download it from the SvmPerf website, and put a link to it in your path.
    at Object.SvmPerf (C:\Users\c\Desktop\package\classifiers\svm\SvmPerf.js:29:10)
    at Object.<anonymous> (C:\Users\c\Desktop\package\classifiers\svm\SvmPerfDemo.js:16:18)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)

C:\Users\c\Desktop\package\classifiers\svm>

**Comment by vaskonov** [comment]
@corradodebari, I think you can try to update the environment variable in Windows and to include the path to the `svm_perf_learn`, alternativelly you can try to copy `svm_perf_learn` to `%SystemRoot%\system32`
and rerun `node SvmPerfDemo.js`

**Comment by corradodebari** [comment]
Hi. Finally I've found the issue.
In SvmPerf.js the checking of svm_perf_learn.exe  is done executing this command:
**var result = execSync("svm_perf_learn -c 1 a");**
the fault is related to the fact that trainingSet file "a" doesn't exist.
Modifing in this way:
var result = execSync("svm_perf_learn");
it works.

**Comment by erelsgl** [comment]
I implemented your change. Thanks for the input.
