### ISSUE TITLE
Always the same result for Bayesian classifier

### ISSUE THREAD

**Issue by sqf** [erelsgl/limdu#49]
Hi,
Let's take this example https://github.com/erelsgl/limdu-demo/blob/master/batch_bayesian_explain_serialize.js 
I always get the same result `{ classes: 'white',
  explanation: [ 'white: 0.0621402182289608', 'black: 0.031460948468170505' ] }` no matter what I put as an argument to method classify. In particular shouldn't I get `classes: 'black'` when I make such call `colorClassifier.classify({ r: 0.03, g: 0.7, b: 0.5 }` ?

Br,
Samir

**Comment by erelsgl** [comment]
The Bayesian classifier was built to work with texts, so the numbers should be integers. I fixed both the classifier (in limdu repository) and the demo (in the limdu-demo repository).
