### ISSUE TITLE
limdu.utils.test does not exist.

### ISSUE THREAD

**Issue by gburtini** [erelsgl/limdu#53]
The cross-validation example uses this, and the utils/index.js has it commented out and `trainAndTest.js` has never been committed. Could you commit a copy of it (or post it here) so I can try to add it to the library?

**Comment by oozaa** [comment]
I am looking for limdu.utils.test too.

**Comment by erelsgl** [comment]
I found a version of trainAndTest in another project (https://github.com/erelsgl/nlu-server/tree/master/utils) and rescued it from there. I had to make some changes since it was not entirely compatible with the example. It is still not in npm but you can access it by cloning the project. Please check and see if it helps you.

**Comment by gburtini** [comment]
@erelsgl are you currently still maintaining / developing this library?

**Comment by erelsgl** [comment]
@gburtini I am doing minimal maintenance, I do not have time for active development.

**Comment by oozaa** [comment]
@erelsgl  Thank you for updating github project. It is great!

 I have just quickly ran cross-validation script test, and got many NaN and undefined values. Is this is how it supose to work?
Here is a my results: `
MACRO AVERAGE:
{ labels: {},
  confusion: {},
  count: 42,
  TRUE: 28.450000000000003,
  startTime: 2017-06-02T09:52:08.883Z,
  TP: NaN,
  FN: NaN,
  FP: NaN,
  endTime: '0Fri Jun 02 2017 10:52:09 GMT+0100 (BST)',
  timeMillis: 6.4,
  timePerSampleMillis: 0.1523809523809524,
  Accuracy: 0.6773809523809524,
  macroPrecision: NaN,
  macroRecall: NaN,
  macroF1: NaN,
  microPrecision: NaN,
  microRecall: NaN,
  microF1: NaN,
  HammingLoss: NaN,
  HammingGain: NaN,
  shortStatsString: 'Accuracy=68% HammingGain=NaN% Precision=NaN% Recall=NaN% F1=NaN% timePerSample=0[ms]' }


MICRO AVERAGE:
{ labels: {},
  confusion: {},
  count: 840,
  TRUE: 569,
  startTime: 2017-06-02T09:52:08.883Z,
  TP: undefined,
  FN: undefined,
  FP: undefined,
  endTime: 2017-06-02T09:52:18.430Z,
  timeMillis: 9547,
  timePerSampleMillis: 11.36547619047619,
  Accuracy: 0.6773809523809524,
  macroPrecision: NaN,
  macroRecall: NaN,
  macroF1: NaN,
  microPrecision: NaN,
  microRecall: NaN,
  microF1: NaN,
  HammingLoss: NaN,
  HammingGain: NaN,
  shortStatsString: 'Accuracy=569/840=68% HammingGain=1-NaN/NaN=NaN% Precision=NaN% Recall=NaN% F1=NaN% timePerSample=11[ms]' }
`

**Comment by erelsgl** [comment]
@oozaa What code exactly did you run?

**Comment by oozaa** [comment]
@erelsgl https://kobra.io/#/e/-KlcZDLYLQVwCUMM7lAl

**Comment by erelsgl** [comment]
I recovered a working version of PrecisionRecall from here: https://github.com/erelsgl/limdu/blob/d61166c91a81daee62e3d67d5fff2b06cee8191f/utils/PrecisionRecall.js now it looks better.

**Comment by oozaa** [comment]
@erelsgl  I have just tested with the new PrecisionRecall.js , it works fine now, and gives some values instead of returning NaN and undefined. 

Thank you!
