### ISSUE TITLE
Does limdu support json file for saving and loading classifier?

### ISSUE THREAD

**Issue by deathg0d** [erelsgl/limdu#56]
If it does, could we have a documentation for it?
For example: https://www.npmjs.com/package/natural-synaptic

**Comment by erelsgl** [comment]
Limdu supports serialization using the serialization.js package. See documentation here:
https://github.com/erelsgl/limdu#serialization

**Comment by deathg0d** [comment]
Yes, I realized it a little late. Thanks anyway :)
