### ISSUE TITLE
This package is no longer usable because "brain" library has been removed

### ISSUE THREAD

**Issue by Pierre-Gilles** [erelsgl/limdu#57]
Hey !

First thank you for your awesome module :)

I'm the founder of [Gladys](https://github.com/GladysProject/Gladys), an open-source home automation assistant written in Node.js. 

We are using `limdu` as a dependency, and since this week the installation of Gladys is broken because the dependency [brain](https://www.npmjs.com/package/brain) that is used in limdu has been deprecated and is no longer possible to install.

I saw that there is a community fork called [brain.js](https://github.com/BrainJS/brain.js), I don't know if it supports all features used in limdu, but if yes maybe limdu could switch from the deprecated "brain" to "brain.js". 

If you think that's a good idea, I can submit a PR to help you make this module work again :)

**Comment by erelsgl** [comment]
Dear Pierre,
yes, I think this is a good idea. You are welcome to submit a PR.

*--- Erel Segal-Halevi   (http://erelsgl.github.io
<http://erelsgl.github.io>) אראל סגל הלוי*

**Comment by Pierre-Gilles** [comment]
I tried to switch from brain to brain.js. It worked !

Just one issue, I ran your test, and they are not all working (even without my changes with the old brain library) =>

<img width="592" alt="capture d ecran 2018-02-18 a 13 19 55" src="https://user-images.githubusercontent.com/7365207/36351742-9b4df51a-14ae-11e8-8445-4a325c7bf3cf.png">

I don't know if you see the problem or not... 

I can submit the PR without the test passing but that may not be a good idea. Maybe it may be a good moment to make everything works again :)

Thanks again for your answer,

**Comment by erelsgl** [comment]
Thanks! I merged the PR.
Regarding the failing tests - I have to check it, but currently I am
overloaded with teaching duties.

*--- Erel Segal-Halevi   (http://erelsgl.github.io
<http://erelsgl.github.io>) אראל סגל הלוי*

**Comment by Pierre-Gilles** [comment]
No problem I understand, thank you very much for being that fast :) 

Can you bump your module version to `0.9.4`, and publish a new version to NPM with this change ? :) 

Thx!

**Comment by erelsgl** [comment]
Done, please verify

*--- Erel Segal-Halevi   (http://erelsgl.github.io
<http://erelsgl.github.io>) אראל סגל הלוי*

**Comment by Pierre-Gilles** [comment]
Built are passing again, yeaah 🤘

<img width="1126" alt="capture d ecran 2018-02-18 a 18 08 21" src="https://user-images.githubusercontent.com/7365207/36354562-c3a239a4-14d6-11e8-9c67-2be389effb6c.png">

You're my hero of today, thanks a lot for being so reactive :)

Thank you from the whole Gladys community 🙂

**Comment by robertleeplummerjr** [comment]
You guys rock.  Anything bugs found in brain.js, let us know.
