### ISSUE TITLE
How do I know the progress of Training?

### ISSUE THREAD

**Issue by tvvignesh** [erelsgl/limdu#60]
First of all, great work with this library. While it works for small data sets. I wanted to do the same for large datasets. It looks like it is stuck in trainbatch and I am not sure about the progress of the training completed so far.

How do I know how many records have been trained so far or get some feedback that its processing?

**Comment by tvvignesh** [comment]
Hmm. I managed for now by passing debug as true to the options like so:

```
var TextClassifier = limdu.classifiers.multilabel.BinaryRelevance.bind(0, {
        binaryClassifierType: limdu.classifiers.SvmJs.bind(0, { C: 1.0 }),
        debug: true
});
```

And doing that I noticed that SvmJs gets stuck with the first input itself if the size of the input of dataset is more than 250 rows or so and does not train further (waited for around 15-20 minutes).

Hence, I had to go far WordExtractor + Winnow classifier like so:
```
var TextClassifier = limdu.classifiers.multilabel.BinaryRelevance.bind(0, {
        binaryClassifierType: limdu.classifiers.Winnow.bind(0, { retrain_count: 10 }),
        debug: true
});
```

Thanks anyways for your reply.

**Comment by erelsgl** [comment]
Interesting. So is this a bug in SvmJS?

*--- Erel Segal-Halevi   (http://erelsgl.github.io
<http://erelsgl.github.io>) אראל סגל הלוי*

**Comment by tvvignesh** [comment]
Not sure if its a bug (since it did not throw any error or so) but there is an issue which has been raised and a pull request merged here: https://github.com/karpathy/svmjs/issues/5

**Comment by erelsgl** [comment]
Hi Vignesh,

As far as I remember, the files created by SvmPerf are just input files
sent to the svm_perf binary, and output files created by the svm_perf
binary.   So, if your training data and parameters are not changed, you can
re-use them.

Regarding production environment, I think the only reliable answer can be
found by experimenting..



*--- Erel Segal-Halevi   (http://erelsgl.github.io
<http://erelsgl.github.io>) אראל סגל הלוי*
