### ISSUE TITLE
Visualize Correlations between data?

### ISSUE THREAD

**Issue by vince-lynch** [erelsgl/limdu#61]
Hi I'm using the Online Learning module.
I want to see somehow how data is connected, I'm happy to make charts/diagrams in D3 etc, but just working out what kind of output I can get, 

Any advice would be great, 
Thankyou.
Vince.

**Comment by erelsgl** [comment]
Hi Vince,
I am not very experienced with d3 so I am not sure how I can help you..

*--- Erel Segal-Halevi   (http://erelsgl.github.io
<http://erelsgl.github.io>) אראל סגל הלוי*

**Comment by vince-lynch** [comment]
Ah,  but is there any way of seeing a JSON or something, or a javascript object about the inner workings of the classifier. or is there a file its stored in?

**Comment by erelsgl** [comment]
I think you should be able to print a classifier to JSON.
There are also examples in the main page about how to "serialize" a
classifier;
the serialization is text-based so you should be able to read it.
*--- Erel Segal-Halevi   (http://erelsgl.github.io
<http://erelsgl.github.io>) אראל סגל הלוי*
