### ISSUE TITLE
Security Notice & Bug Bounty - Command Injection - huntr.dev

### ISSUE THREAD

**Issue by huntr-helper** [erelsgl/limdu#70]
# Overview

limdu is an A machine learning framework for Node.js. Supports multi-level classification and online learning.

This package is vulnerable to Command Injection through the `trainBatch` function.

# Bug Bounty

We have opened up a bounty for this issue on our bug bounty platform. Want to solve this vulnerability and get rewarded 💰? Go to https://huntr.dev/

We will submit a pull request directly to your repository with the fix as soon as possible. Want to learn more? Go to https://github.com/418sec/huntr 📚

_Automatically generated by @huntr-helper..._

**Comment by erelsgl** [comment]
spam

**Comment by JamieSlome** [comment]
Apologies! We hit a false positive here, we are removing the bounty from our platform.

Cheers! 🍰

**Comment by huntr-helper** [comment]
### Bug Bounty

We have opened up a bounty for this issue on our bug bounty platform. Want to solve this vulnerability? Go to https://huntr.dev/

We will submit a pull request directly to your repository with the fix as soon as possible. Want to learn more? Go to https://github.com/418sec/huntr 📚

_Automatically generated by @huntr-helper..._
